const m = require("mithril")
const _ = require("underscore")

let Hotel = {
  compareThis: (hotel)=>{
    let dupeCheck = _.contains(Hotel.compare, hotel) //check if item is extant in comparison array
    if(dupeCheck === true) { return } //oops already exists. dont add again
    Hotel.compare.push(hotel) // we're good, it's non-existant. lets add it to the array
  },
  setCurrent: () => {},
  compare: [],
  current: {
    name: "",
    address: "",
    salesOffice: { phone: "", email: ""},
    website: "",
    twitter: "",
    directorOfSales: "",
    directorOfCatering: "",
    sleepingRooms: 0,
    roomsTax: "",
    resortFee: "",
    wifiFee: "",
    parking: "",
    meetingSpace: { capacityChart: "", floorPlan: "" },
    largestRooms: [{ name: "", sqft: ""}, { name: "", sqft: ""}],
    meetingRoomCount: 0,
    publicWifiSpace: "",
    avCompany: {name: "", menu: ""},
    businessCenter: { description: "", onsite: true, hours: "", telephone: "" },
    banquetMenu: "",
    salesTax: "",
    serviceCharge: "",
    customMenuAvailable: true,
    hotelRating: "",
    loyaltyProgram: {available: true, name: ""},
    union: true,
    airport: { name: "", distance: "", abbreviation: "" },
    restaurants: [{name: "", menu: ""}],
    fitnessCenter: true,
    pool: { available: true, indoor: true },
    spa: { available: true, name: "", website: "" },
    pointsOfInterest: [{name: "", distance: "", description: ""}]
  },
  list: [
    {
      name: "Hyatt Regency Washington on Capitol Hill",
      address: "400 New Jersey Ave, NW Washington, DC 20001",
      salesOffice: { phone: " 202-197-1234", email: "wasrw@hyatt.com"},
      website: "hyattregencywashington.com",
      twitter: "hyattwashington",
      directorOfSales: "Ray Messina",
      directorOfCatering: "Dustin Imbesi",
      sleepingRooms: 838,
      roomsTax: "14.5%",
      resortFee: "N/A",
      wifiFee: "$9.99 per day",
      parking: {self: "$9.99 per day", valet: "$62 per day"},
      meetingSpace: { capacityChart: "Capacity Chart", floorPlan: "Floor Plan" },
      largestRooms: [{ name: "", sqft: "38,000"}, { name: "", sqft: "3,588"}],
      meetingRoomCount: 32,
      publicWifiSpace: "Complimentary",
      avCompany: {name: "PSAV", menu: ""},
      businessCenter: { description: "Fedex Office", onsite: true, hours: {}, telephone: "" },
      banquetMenu: "MENU",
      salesTax: "10%",
      serviceCharge: "24%",
      customMenuAvailable: true,
      hotelRating: "AAA 3 Diamond",
      loyaltyProgram: {available: true, name: "Hyatt Gold Passport"},
      union: true,
      airport: { name: "DCA", distance: "5.4 miles", abbreviation: "DCA" },
      restaurants: [{name: "restaurants", menu: ""}],
      fitnessCenter: true,
      pool: { available: true, indoor: true },
      spa: { available: false, name: "", website: "" },
      pointsOfInterest: [{name: "", distance: "", description: ""}]
    },
    {
      name: "Hard Rock Hotel & Casino Las Vegas",
      address: "4455 Paradise Road, Las Vegas, NV 89169",
      salesOffice: { phone: "855-693-5500", email: "sales@hrhvegas.com"},
      website: "hardrockhotel.com",
      twitter: "hardrockhotellv",
      directorOfSales: "N/A",
      directorOfCatering: "N/A",
      sleepingRooms: 1504,
      roomsTax: "13.38%",
      resortFee: "$35.15 per day",
      wifiFee: "Included in resort fee",
      parking: {self: "Complimentary", valet: "Complimentary"},
      meetingSpace: { capacityChart: "Capacity Chart", floorPlan: "Floor Plan" },
      largestRooms: [{ name: "Muse Hall", sqft: "15,720"}, { name: "Artist Hall", sqft: "10,200"}],
      meetingRoomCount: 0,
      publicWifiSpace: "Included in resort fee",
      avCompany: {name: "Encore", menu: ""},
      businessCenter: { description: "", onsite: true, hours: {weekdays: "7am - 6pm", saturday: "9am - 4pm", sunday: "10am - 4pm"}, telephone: "702-216-5361" },
      banquetMenu: "MENU",
      salesTax: "8.25%",
      serviceCharge: "22%",
      customMenuAvailable: true,
      hotelRating: "AAA 4 Diamond",
      loyaltyProgram: {available: true, name: "Backstage Pass"},
      union: false,
      airport: { name: "McCarran International Airport", distance: "1.6 miles", abbreviation: "LAS" },
      restaurants: [{name: "restaurants", menu: ""}],
      fitnessCenter: true,
      pool: { available: true, indoor: false },
      spa: { available: true, name: "Reliquary Spa", website: "" },
      pointsOfInterest: [{name: "", distance: "", description: ""}]
    },
    {
      name: "Red Rock Casino Resort & Spa",
      address: "11011 West Charleston Blvd, Las Vegas, NV 89135",
      salesOffice: { phone: "866-767-7774", email: "sales@hrhvegas.com"},
      website: "redrock.sclv.com",
      twitter: "redrockcasino",
      directorOfSales: "N/A",
      directorOfCatering: "N/A",
      sleepingRooms: 1504,
      roomsTax: "13.38%",
      resortFee: "$35.15 per day",
      wifiFee: "Included in resort fee",
      parking: {self: "Complimentary", valet: "Complimentary"},
      meetingSpace: { capacityChart: "Capacity Chart", floorPlan: "Floor Plan" },
      largestRooms: [{ name: "Muse Hall", sqft: "15,720"}, { name: "Artist Hall", sqft: "10,200"}],
      meetingRoomCount: 0,
      publicWifiSpace: "Included in resort fee",
      avCompany: {name: "Encore", menu: ""},
      businessCenter: { description: "", onsite: true, hours: {weekdays: "7am - 6pm", saturday: "9am - 4pm", sunday: "10am - 4pm"}, telephone: "702-216-5361" },
      banquetMenu: "MENU",
      salesTax: "8.25%",
      serviceCharge: "22%",
      customMenuAvailable: true,
      hotelRating: "AAA 4 Diamond",
      loyaltyProgram: {available: true, name: "Backstage Pass"},
      union: false,
      airport: { name: "McCarran International Airport", distance: "1.6 miles", abbreviation: "LAS" },
      restaurants: [{name: "restaurants", menu: ""}],
      fitnessCenter: true,
      pool: { available: true, indoor: false },
      spa: { available: true, name: "Reliquary Spa", website: "" },
      pointsOfInterest: [{name: "", distance: "", description: ""}]
    },
    {
      name: "Green Valley Ranch Casino and Spa",
      address: "11011 West Charleston Blvd, Las Vegas, NV 89135",
      salesOffice: { phone: "866-767-7774", email: "sales@hrhvegas.com"},
      website: "redrock.sclv.com",
      twitter: "redrockcasino",
      directorOfSales: "N/A",
      directorOfCatering: "N/A",
      sleepingRooms: 1504,
      roomsTax: "13.38%",
      resortFee: "$35.15 per day",
      wifiFee: "Included in resort fee",
      parking: {self: "Complimentary", valet: "Complimentary"},
      meetingSpace: { capacityChart: "Capacity Chart", floorPlan: "Floor Plan" },
      largestRooms: [{ name: "Muse Hall", sqft: "15,720"}, { name: "Artist Hall", sqft: "10,200"}],
      meetingRoomCount: 0,
      publicWifiSpace: "Included in resort fee",
      avCompany: {name: "Encore", menu: ""},
      businessCenter: { description: "", onsite: true, hours: {weekdays: "7am - 6pm", saturday: "9am - 4pm", sunday: "10am - 4pm"}, telephone: "702-216-5361" },
      banquetMenu: "MENU",
      salesTax: "8.25%",
      serviceCharge: "22%",
      customMenuAvailable: true,
      hotelRating: "AAA 4 Diamond",
      loyaltyProgram: {available: true, name: "Backstage Pass"},
      union: false,
      airport: { name: "McCarran International Airport", distance: "1.6 miles", abbreviation: "LAS" },
      restaurants: [{name: "restaurants", menu: ""}],
      fitnessCenter: true,
      pool: { available: true, indoor: false },
      spa: { available: true, name: "Reliquary Spa", website: "" },
      pointsOfInterest: [{name: "", distance: "", description: ""}]
    },
  ],
  load: ()=>{}
}

module.exports = Hotel
